export { default as LoginForm } from "./login/form";
export { default as Table } from "./table/table-type";
export { default as TableTab } from "./tableTab/index";
export { default as ProductModal } from "./productModal/index";
export { default as BasicInformation } from "./productModal/basic-form";
export { default as CategoryModal } from "./categoryModal/index";
export { default as CategoryForm } from "./categoryModal/basic-form";
export { default as SideBard } from "./SideBar/index";
export { default as OrderCard } from "./orderCard/index";
